#!/usr/bin/env Rscript
# Check reverse dependencies
require("devtools")
devtools.revdep.libpath = "../irace.revdep"
options(devtools.revdep.libpath = devtools.revdep.libpath)
if (!dir.exists(devtools.revdep.libpath)) dir.create(devtools.revdep.libpath)
revdep_check_resume()
# This fails with:

## trying URL 'https://cran.rstudio.com/src/contrib/rJava_0.9-9.tar.gz'
## Content type 'application/x-gzip' length 660454 bytes (644 KB)
## ==================================================
## downloaded 644 KB

## Error: Command failed (1)
