#!/usr/bin/env Rscript
## require("tools")

## options(repos = 'http://cran.rstudio.com/')
## pdb <- available.packages()
## deps <- package_dependencies(packages = "irace", pdb, reverse = TRUE)
## tools::check_packages_in_dir(dir = "/tmp", reverse = deps)

# Check reverse dependencies
require("devtools")

libpath = file.path(tempdir(), "R-lib")
dir.create(libpath)

pkg = read.dcf("DESCRIPTION")[[1,"Package"]]
deps = revdep(pkg)

install.packages(deps, lib = libpath, repos = 'http://cran.rstudio.com/')
ok = check_cran(deps, libpath = libpath)

if(!all(sapply(ok, is.null))) {
  f = names(Filter(function(x) !is.null(x), ok))
  stop(sprintf("Some packages failed the test: %s", paste(f, collapse=", ")))
}

message("All reverse dependencies ok!")
