#!/bin/sh
rm -f  irace-Ex.R config.* confdefs.h \
   src/*.so src/*.o src/*/*.o src/*.gcno src/*/*.gcno src/config.h src/symbols.rds \
   inst/doc/*.blg inst/doc/*.bbl \
   tests/testthat/*.log tests/testthat/*.Rout tests/testthat/irace.Rdata

find . -name '*.orig' -o -name '.Rhistory' -o -name '*.rej' | xargs rm -f

rm -rf autom4te.cache

rm -f examples/vignette-example/Rplots.pdf

