#!/bin/sh
rm -f  irace-Ex.R config.* confdefs.h \
   src/*.so src/*.o src/*/*.o src/*.gcno src/*/*.gcno src/*.gcov src/config.h src/symbols.rds \
   inst/doc/*.blg inst/doc/*.bbl \
   tests/testthat/*.log tests/testthat/*.Rout tests/testthat/Rplots.pdf tests/testthat/iracedump.rda tests/testthat/irace.Rdata

rm -fr  tests/testthat/run_* tests/testthat/multi_irace*

find . -name '*.orig' -o -name '.Rhistory' -o -name '*.rej' | xargs rm -f

rm -rf autom4te.cache

rm -f examples/vignette-example/Rplots.pdf
rm -f devel-examples/vignette-example/*.stderr devel-examples/vignette-example/*.stdout


