#!/bin/bash
###############################################################################
# This script is run after all candidate configurations have been run on
# a single instance. 
#
# PARAMETERS:
# $1 is the candidate  configuration number
# $2 is the instance id
# $3 is the seed
# $4 is the instance name
# $5 is the number of candidates alive in this iteration
#
# ONLY FOR ELITIST RACE: The rest ($* after `shift 5') are the ids of the 
# candidates alive in this iteration. This list can be used to calculate the 
# hypervolume using previous execution results.
#
# RETURN VALUE:
# This script should print a single numerical value
###############################################################################
CANDIDATE="$1"
INSTANCEID="$2"
SEED="$3"
INSTANCE="$4"
NUMCAND="$5"
shift 5 || error "Not enough parameters to $0"
ALLIDS=$*


while [ -s "$NUMCAND" ]; do
    sleep 10
done

COST=`cat ${NUMCAND}.run.output | grep -e '^[0-9]' | cut -f1`
echo "$COST"
rm -f ${NUMCAND}.run.output ${NUMCAND}.run.stderr
#exit 0

