#!/bin/bash
###############################################################################
# This hook is the command that is executed every run.
# Check the examples in examples/
#
# This hook is run in the execution directory (execDir, --exec-dir),
# the same directory where hook-evaluate is executed. Hence, you may
# need to copy extra files needed by the executable to this directory.
#
# PARAMETERS:
# $1 is the instance name
# $2 is the candidate number
# The rest ($* after `shift 2') are parameters to the run
#
# RETURN VALUE:
# This script should print nothing.
# Exit with 0 if no error, with 1 in case of error
###############################################################################

EXE=~/bin/Spear-32_1.2.1
TIMEOUT=30
FIXED_PARAMS="--nosplash --time --tmout $TIMEOUT"
INSTANCE=$1
CANDIDATE=$2
shift 2 || exit 1
CAND_PARAMS=$*

$EXE ${FIXED_PARAMS} --dimacs $INSTANCE ${CAND_PARAMS} 1> c${CANDIDATE}.stdout 2> c${CANDIDATE}.stderr
if [ $? -ne 0 ]; then
    (cat <<EOF
c ERROR
c runtime 30
EOF
    ) > c${CANDIDATE}.stdout
fi

exit 0
