#!/bin/bash
###############################################################################
# This hook is the command that is executed every run.
# Check the examples in examples/
#
# PARAMETERS:
# $1 is the candidate number
# $2 is the instance name
# The rest ($* after `shift 2') are parameters to the run
#
# RETURN VALUE:
# This script should print nothing.
# Exit with 0 if no error, with 1 in case of error
###############################################################################

EXE=~/bin/moaco_btsp
FIXED_PARAMS="--trials 1 --time 60 --wls 1 --PACO --candidate-list 40"
CANDIDATE=$1
INSTANCE=$2
shift 2
CAND_PARAMS=$*

exec $EXE ${FIXED_PARAMS} --input $INSTANCE ${CAND_PARAMS} --output ${CANDIDATE}.output &> ${CANDIDATE}.stderr
