#!/bin/sh

BINDIR=$1
EXECDIR=$2
shift 2

qsub <<EOF
#!/bin/sh
#$ -N ifrace-$$
#$ -l opteron2216
#$ -l long
#$ -o $EXECDIR/ifrace-$$.stdout
#$ -e $EXECDIR/ifrace-$$.stderr
#$ -cwd

$BINDIR/ifrace $EXECDIR $* 

EOF

