#!/bin/bash
###############################################################################
# This hook is to tune the ACOTSP software.
#
# PARAMETERS:
# $1 is the instance name  
# $2 is the candidate number
# The rest ($* after `shift 2') are parameters to the run of ACOTSP
#
# RETURN VALUE:
# This script print nothing but call ACOTSP.
###############################################################################

# Path to the ACOTSP software:
EXE=~/bin/acotsp

# What "fixed" parameters should be always passed to ACOTSP?
# The time to be used is always 5 seconds, and we want only one run:
FIXED_PARAMS=" --time 5 --tries 1 "

# The instance name and the candidate id are the first parameters
INSTANCE=$1
CANDIDATE=$2

# All other parameters are the candidate parameters to be passed to ACOTSP
shift 2 || exit 1
CAND_PARAMS=$*

# Now we can call ACOTSP by building a command line with all parameters for it
exec $EXE ${FIXED_PARAMS} -i $INSTANCE ${CAND_PARAMS} 1> c${CANDIDATE}.stdout 2> c${CANDIDATE}.stderr
