#!/bin/bash
###############################################################################
# This hook is the command that is executed every run.
#
# PARAMETERS:
# $1 is the candidate number
# $2 is the instance name
# The rest are parameters to the run
#
# RETURN VALUE:
# This script should print nothing.
# Exit with 0 if no error, with 1 in case of error
###############################################################################

EXE=/home/manu/personal/iterated-f-race/jeremie/Program/beamaco_tsptw
CANDIDATE=$1
INSTANCE=$2
shift 2
exec $EXE -S 1 --time 1 -r 1 -i $INSTANCE $* 1> ${CANDIDATE}.run.output 2> ${CANDIDATE}.run.stderr


